const Map<String , String> ar = {
  "selectLanguage" : "تحديد لغة التطبيق",
  "next" : "التالي" ,
  "welcome to our team @" : "مرحبًا بك في تيم  @",
  "social app"  : "تطبيق اجتماعي",
  "Enter your mobile number, we will send a cade to your number" : "أدخل رقم هاتفك المحمول ، وسنرسل رمزًا إلى رقمك" ,
   "Continue" : "استمرار" ,
  "Verify your mobile number" : "تحقق من رقم هاتفك المحمول" ,
  "Enter the pin you have received via SMS on" : "أدخل الرقم السري الذي تلقيته عبر رسالة" ,
  "Set your location so you can see the neighboring groups " : "حدد موقعك حتى تتمكن من رؤية المجموعات" ,
  "Team @ talk any person of your" : "تيم @ للتعامل مع أي شخص ",
  "mother language" :"لغتك الام",
  "Let's Sign you in" : "دعنا نسجل دخولك" ,
  "Welcome back we have been missed" : "مرحبا بعودتك فقد افتقدنا",
  "Email" : "بريد الالكتروني" ,
  "password" : "كلمة المرور" ,
  "Forget password ?" : "هل نسيت كلمة السر ؟",
  "Sign in" : "تسجيل الدخول" ,
  "Don't have an account?" : "ليس لديك حساب" ,
  "Sign Up" : "انشاء حساب جديد",
  "Creating an account to continue" : "إنشاء حساب للمتابعة",
  "UserName" : "اسم المستخدم",
  "Enter your mobile number" : "أدخل رقم هاتفك المحمول",
  "Set your location so you can see the neighboring groups" :
  "حدد موقعك حتى تتمكن من رؤية المجموعات",
  "Enter your location" : "أدخل موقعك",
  "GettingStart" : "دعنا نبدا",
  "Set your profile photo and your name" : "حدد صورتك الشخصية و اسمك",
  "Bio" : "السيره الذاتية" ,
  "Set your location" : "حدد موقعك",
  "emailEmpty" :"البريد الالكتروني فارغ",
  "passwordEmpty" : "الرقم السري فارغ",
  "userNameEmpty" : "اسم المستخدم فارغ",
  "lengthError" : "يجب ان يكون الرقم السري اكثر من 6",
  "badForm" : "هذا البريد الالكتروني غير صالح",
  "BioEmpty" : "حقل لمعلومات فارغ" ,
  "selectImage" : "حدد صورة" ,
  "chooseAway" : "اختر طريقه لتحميل الصورة" ,
  "FromGallery" : "من الاستديو" ,
  "fromCamera" : "من الكاميرا",
  "locationError" : "خطا في الموقع",
  "selectLocation" : "من فضلك حدد موقعك",
  "Home" : "العامة" ,
  "Profile" : "حسابي" ,
  "Chats" : "المحادثات" ,
  "Groups" : "المجموعات" ,
  "numberError" : "الرقم الذي ادخلتة غير صحيح من فضلك ارجع وتاكد من الرقم",
  "emptyImage" : "صورة فارغة",
  "imageEmpty" : "حدد صورتك الشخصية",
  "noPosts" : "لا يوجد منشورات لعرضها",
  "Select Group" : "اختر مجموعة" ,
  "Search for Group" : "ابحث عن مجموعه" ,
  " Likes" :" اعجاب" ,
  " Comments" :" تعليق" ,
  "0 Comments" : "0 تعليق" ,
  "Time Line is empty" : "الصفحة الرئيسية فارغة" ,
  "Searching For Posts" : "جاري البحث عن منشورات" ,
  "My Groups" : "مجموعاتي" ,
  "No Groups Created" : "لا توج مجموعات حاليا" ,
  "Other Groups" : "المجموعات الاخري",
  "No Groups To Join" : "لا توجد مجموعات حاليا" ,
  "My Groups Chats" : "دردشات مجموعاتي" ,
  "Posts" : "المنشورات" ,
  "My groups" : "مجموعاتي" ,
  "Following groups" : "المجموعات المتابعة" ,
  "My Bio" : "وصفي" ,
  "Edit group" : "تعديل" ,
  "Leave Group" : "مغادره" ,
  "cancel request" : " الغاء الطلب" ,
  "Join Group" : "انضمام",
  "About group" : "عن المجموعه" ,
  "Request Not Valid" :"خطا في الطلب" ,
  "Please join to the group" : "من فضلك انضم للمجموعة" ,
  "admin": "مؤسس",
  "Member" :"عضو" ,
  "Members" :"الاعضاء",
  "Please join to the group tp up Posts" : "من فضلك انضم للمجموعة لتتمكن من نشر منشورات",
  "Message" : "الرسائل" ,
  "Please join to the group to Starting Chat" : "من فضلك انضم للمجموعه لتتمكن من الدردشة" ,
  " Chat" : "دردشه" ,
  "Write a message" : "اكتب رسالة" ,
  "Comments" : "التعليقات" ,
  "view all comments" : "عرض كل التعليقات" ,
  "Comment Error" : "خطا في التعليق" ,
  "Please Enter Comment" : "من فضلك اكتب تعليق " ,
  "Write a comment" : "اكتب تعليق" ,
  "Requests" : "طلبات الانضمام" ,
  "Accept" : "قبول" ,
  "Refuse" : "رفض" ,
  "Group Name Is Empty" : "اسم المجموعة فارغ" ,
  "Name group" : "اسم المجموعة" ,
  "Group details" : "معلومات المجموعة" ,
  "erorr" : "خطا" ,
  "Please add Desciption" : "من فضل ادخل وصف" ,
  "Create group" : "انشاء مجموعة" ,
  "Create Post" : "انشاء منشور" ,
  "Post" : "نشر",
  "admin of group" : "منظم المجموعة" ,
  "member in group" : "عضو في المجموعة" ,
  "What\'s in your mind ?" : "ماذا يدور بعقلك" ,
  "Camera" :"كاميرا" ,
  "Photos" : "صوري" ,
  "Please select Image" : "من فضلك املي جميع البيانات",
  "Image Error" : "خطا في الطلب" ,
  "Save Changes" : "حفظ التعديلات" ,
  "Edit Post" :"تعديل المنشور" ,
  "username" : "اسم المستخدم" ,
  "phone" : "الهاتف",
  "Location" : "الموقع" ,


};