const Map<String , String> ar = {
  "selectLanguage" : "تحديد لغة التطبيق",
  "next" : "التالي" ,
  "welcome to our team @" : "مرحبًا بك في تيم  @",
  "social app"  : "تطبيق اجتماعي",
  "Enter your mobile number, we will send a cade to your number" : "أدخل رقم هاتفك المحمول ، وسنرسل رمزًا إلى رقمك" ,
   "Continue" : "استمرار" ,
  "Verify your mobile number" : "تحقق من رقم هاتفك المحمول" ,
  "Enter the pin you have received via SMS on" : "أدخل الرقم السري الذي تلقيته عبر رسالة" ,
  "Set your location so you can see the neighboring groups " : "حدد موقعك حتى تتمكن من رؤية المجموعات" ,
  "Team @ talk any person of your" : "تيم @ للتعامل مع أي شخص ",
  "mother language" :"لغتك الام",
  "Let's Sign you in" : "دعنا نسجل دخولك" ,
  "Welcome back we have been missed" : "مرحبا بعودتك فقد افتقدنا",
  "Email" : "بريد الالكتروني" ,
  "password" : "كلمة المرور" ,
  "Forget password ?" : "هل نسيت كلمة السر ؟",
  "Sign in" : "تسجيل الدخول" ,
  "Don't have an account?" : "ليس لديك حساب" ,
  "Sign Up" : "انشاء حساب جديد",
  "Creating an account to continue" : "إنشاء حساب للمتابعة",
  "UserName" : "اسم المستخدم",
  "Enter your mobile number" : "أدخل رقم هاتفك المحمول",
  "Set your location so you can see the neighboring groups" :
  "حدد موقعك حتى تتمكن من رؤية المجموعات",
  "Enter your location" : "أدخل موقعك",
  "GettingStart" : "دعنا نبدا",
  "Set your profile photo and your name" : "حدد صورتك الشخصية و اسمك",
  "Name" : "الاسم" ,
  "Set your location" : "حدد موقعك",
  "emailEmpty" :"البريد الالكتروني فارغ",
  "passwordEmpty" : "الرقم السري فارغ",
  "userNameEmpty" : "اسم المستخدم فارغ",
  "lengthError" : "يجب ان يكون الرقم السري اكثر من 6",
  "badForm" : "هذا البريد الالكتروني غير صالح",
  "nameEmpty" : "حقل الاسم فارغ" ,
  "selectImage" : "حدد صورة" ,
  "chooseAway" : "اختر طريقه لتحميل الصورة" ,
  "FromGallery" : "من الاستديو" ,
  "fromCamera" : "من الكاميرا",
  "locationError" : "خطا في الموقع",
  "selectLocation" : "من فضلك حدد موقعك",
  "Home" : "العامة" ,
  "Profile" : "حسابي" ,
  "Chats" : "المحادثات" ,
  "Groups" : "المجموعات" ,


};